### PR TITLE
YSP-490, 501, 502, 503, 514: Add Tiles, Facts and Figures, Quote Callout, and Link Grid Blocks

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- Wires the Tiles component in Drupal, adds `center` option
- Wires the Quote Callout component in Drupal, renames the component from Standalone Quote
- Wires the Facts and Figures component in Drupal, adds column options
- Wires the Link Grid component in Drupal
- Atomic: https://github.com/yalesites-org/atomic/pull/232

### Testing Link(s)
- [ ] Navigate to the [Tiles Component Story](https://deploy-preview-363--dev-component-library-twig.netlify.app/?path=/story/organisms-tiles--tiles&args=image:true)
- [ ] Navigate to the [Quote Callout Component Story](https://deploy-preview-363--dev-component-library-twig.netlify.app/?path=/story/molecules-quotes-quote-callout--quote-callout)
- [ ] Navigate to the [Facts and Figures Component Story](https://deploy-preview-363--dev-component-library-twig.netlify.app/?path=/story/organisms-tiles--tiles&args=image:true)
- [ ] Navigate to the [Link Grid Component Story](https://deploy-preview-363--dev-component-library-twig.netlify.app/?path=/story/organisms-tiles--tiles&args=image:true)

### Functional Review Steps
- [ ] Test in Drupal here: https://github.com/yalesites-org/yalesites-project/pull/638

#### Review in Storybook:
- [x] Navigate to the [Tiles Component Story](https://deploy-preview-363--dev-component-library-twig.netlify.app/?path=/story/organisms-tiles--tiles&args=image:true)
  - [x] Verify it has a `center` option for alignment
- [x] Navigate to the [Quote Callout Component Story](https://deploy-preview-363--dev-component-library-twig.netlify.app/?path=/story/molecules-quotes-quote-callout--quote-callout)
  - [x] Verify the name is Quote Callout - this part of the ticket was focused on renaming the existing component
- [x] Navigate to the [Facts and Figures Component Story](https://deploy-preview-363--dev-component-library-twig.netlify.app/?path=/story/organisms-tiles--tiles&args=image:true)
  - [x] Verify you have column count options
- [ ] Navigate to the [Link Grid Component Story](https://deploy-preview-363--dev-component-library-twig.netlify.app/?path=/story/organisms-facts-and-figures-group--facts-and-figures-group)
- [ ] Verify the component functions as it should - I only made slight refinements while wiring the component to Drupal

### CODE REVIEW

**Comment by codechefmarc** [comment]
I reviewed this on the main PR and have some questions and comments over there. Happy to approve all of these once those are resolved as I don't know if changes are needed here or not.

**Review by dblanken-yale — CHANGES_REQUESTED** [review]
Above you mention verifying column count on Tiles.  I noticed it's labelled "Grid count"--would it make more sense for it to be labelled as "Column count", since "Grid count" could mean a few things.  Same question goes for the Facts and Figures.  My initial thought was "grid count" meant only show x number of items in the grid, not x number of columns.

Also, above for the Facts and Figures link, did you mean this one?  https://deploy-preview-363--dev-component-library-twig.netlify.app/?path=/story/organisms-facts-and-figures-group--facts-and-figures-group

I think it's pointing to the Tiles.

All looks good other than my questions there.  Probably should get other feedback about that, but that was what I noticed.  heh

**Comment by miketullo95** [comment]
@joetower here is the ticket with svg's and descriptions - let me know if that covers everything 
https://yaleits.atlassian.net/jira/software/c/projects/YSP/boards/538?selectedIssue=YSP-516

**Comment by miketullo95** [comment]
@joetower i put this in the yalesites project also, but could we bump up the image size in quote callout?

**Review by nJim — APPROVED** [review]
Work approved in weekly worksession with Kara and Mike T.

**Pull request merged**
