### PR TITLE
YALB-1162 - Cards: Custom cards style updates

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- adds background top color on hover, animates the gradient

### Testing Link(s)
- [ ] Navigate to the [Component Story](https://deploy-preview-XX--dev-component-library-twig.netlify.app/?path=/story/tokens-breakpoints--breakpoints)

### Functional Review Steps
- [ ] Navigate to: https://deploy-preview-231--dev-component-library-twig.netlify.app/?path=/story/organisms-card-collection-custom-card-collection--custom-card-collection&args=featured:false;withImage:false
- [ ] Verify the top border color changes to `blue-light` on hover
- [ ] example: https://user-images.githubusercontent.com/366413/234365410-10bada0a-574d-4784-96f3-c5db7c27bbdc.mp4

### Design Review
- [ ] Verify the designs match the [Figma Designs](https://www.figma.com/file/G4sJ0BLu4jCJpGzW82JHE8/YaleSites-Components?node-id=5778-19212&t=fGb4Wwupx5S4XBUp-0)

### CODE REVIEW

**Comment by ahitson** [comment]
Can we slow down the animation? And verify that it is tied to slots and not a certain color.

The border is still missing from the sitting version.

**Review by nJim — APPROVED** [review]
Straightforward code change. 👍

**Comment by ahitson** [comment]
Almost there. Is there an animation speed that's like 500 or somewhere between? Also, there is only animation on the mouse exit and not the hover. Looking to have it react on both instances.

For the colors, long bar is Slot 1, shorter bar is Slot 2. (Short bar, slot 2 grows on interaction). I'm thinking they wouldn't have dials for now, just one option chosen based on theme.

**Comment by joetower** [comment]
@ahitson Okay, this is ready for you to review again. 

- I added a new token for `animation-speed-medium` and set to `500ms`
- Added global theme options to the card collection
- Set long bar to `slot-one` and short bar to `slot-two`
- I refactored the way the bar is implemented to better animate the bar on hover

https://deploy-preview-231--dev-component-library-twig.netlify.app/?path=/story/organisms-card-collection-custom-card-collection--custom-card-collection&args=globalTheme:two;featured:false;withImage:false

**Comment by joetower** [comment]
@ahitson Pushed more updates: 
- animation speed is now at the default speed of `200ms`
- link:hover colors should change on hover (this is anything using our link mixins - animated underline, no underline, etc. )

Please take another look https://deploy-preview-231--dev-component-library-twig.netlify.app/?path=/story/organisms-card-collection-custom-card-collection--custom-card-collection&args=globalTheme:two;featured:false;withImage:false

Thanks!

**Review by ahitson — APPROVED** [review]

**Pull request merged**
