### PR TITLE
fix(YALB-1555): make tabs appear more clearly defined as tabbed content

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- Updates tab styles to match https://www.figma.com/proto/4Lx9A5sxO08DxUNbewalrR/Yale-Sites---ideation?type=design&node-id=263-4341&t=rYe2BAZtzyh8AnGX-0&scaling=min-zoom&page-id=257%3A514&starting-point-node-id=263%3A4341&show-proto-sidebar=1

### Testing Link(s)
- [ ] Navigate to the [Component Story](https://deploy-preview-294--dev-component-library-twig.netlify.app/?path=/story/molecules-tabs--tabs)

### Functional Review Steps
- [x] Navigate to: https://deploy-preview-294--dev-component-library-twig.netlify.app/?path=/story/molecules-tabs--tabs
- [x] Verify the tab styles to match https://www.figma.com/proto/4Lx9A5sxO08DxUNbewalrR/Yale-Sites---ideation?type=design&node-id=257-1651&t=rYe2BAZtzyh8AnGX-0&scaling=min-zoom&page-id=257%3A514&starting-point-node-id=257%3A1651&show-proto-sidebar=1

Screenshot 2023-09-20 at 5 46 29 PM

- [x] Test in Drupal, which is a more accurate content match for the designs: https://pr-434-yalesites-platform.pantheonsite.io/welcome/text-heavy-content

Screenshot 2023-09-20 at 6 12 55 PM

### Design Review
- [ ] Verify the designs match the [Figma Designs](https://www.figma.com/proto/4Lx9A5sxO08DxUNbewalrR/Yale-Sites---ideation?type=design&node-id=263-4341&t=rYe2BAZtzyh8AnGX-0&scaling=min-zoom&page-id=257%3A514&starting-point-node-id=263%3A4341&show-proto-sidebar=1)

### CODE REVIEW

**Review by codechefmarc — CHANGES_REQUESTED** [review]
Looks great! I do have a minor visual edit if you can: For the CSS for the `.tabs__control--right` there is a `right: var(--size-thickness-1);` that is causing a little bit of the tabs on the right side to "leak out", see screenshot (three dots to the right of the arrow button):

Screenshot 2023-09-25 at 1 23 04 PM

In the inspector, I changed it to use `right: 0` and that seemed to fix it, but not sure if there is a reason to use the spacing variable that I'm unaware of.

**Comment by joetower** [comment]
@codechefmarc Ah, yeah, good call! We no longer need those styles, so I removed them and the spacing on the left and right (of each button, respectively) is now set to `0`.

**Review by codechefmarc — APPROVED** [review]
Yup, that fixed it. I don't see the overflow anymore. Approved!

**Review by dblanken-yale — APPROVED** [review]
Apologize for taking so long!  This looks great.  :D

**Pull request merged**
