### PR TITLE
YALB-1440: Create and theme profile-meta component (FE) | YALB-1436: Create new display modes (FE)

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- Adds new meta component for profiles
- Adds new display mode: `condensed` for `news`, `events`, `profiles`
- Adds new `directory-listing` display mode for `profiles`

### Testing Link(s)
- [ ] New component content type: [Profile Card Component Story](https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--profile-card)
- [ ] New component content type display:  [Profile Card Directory Component Story](https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--profile-card-directory-listing)
- [ ] New display: [Post Card Condensed](https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--post-card&args=collectionType:condensed)
- [ ] New display: [Event Card Condensed](https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--event-card&args=collectionType:condensed)
- [ ] New display: [Profile Card Condensed](https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--profile-card&args=collectionType:condensed)
- [ ] New display: [Profile Card List](https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--profile-card&args=collectionType:list)
- [ ] New display: [Profile Card Grid](https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--profile-card)
- [ ] New display: [Profile Card Collection Grid, List and Condensed ](https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/organisms-card-collection--profile-card-collection)
- [ ] New display: [Profile Directory Card Collection Grid - non-featured](https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/organisms-card-collection--directory-listing-card-collection&args=featured:false)
- [ ] New display: [Profile Directory Card Collection Grid - featured](https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/organisms-card-collection--directory-listing-card-collection)

#### Testing YALB-1440: Create and theme profile-meta component (FE)

- [x] Navigate to https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/molecules-meta--profile
  - [x] Verify there is a new page example for `Profile`: https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/page-examples-profiles--profile-page
  - [x] Verify it matches the [designs](https://www.figma.com/proto/G4sJ0BLu4jCJpGzW82JHE8/YaleSites-Components?type=design&node-id=8239-26166&t=tPPrKP3gmj8tU8EI-0&scaling=min-zoom&page-id=8239%3A26166) 

https://github.com/yalesites-org/component-library-twig/assets/366413/efa0a81e-5c63-4016-a16f-a27f252ab974

---

##### Cards
- [x] Navigate to the [Profile Directory Card Component Story](https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--profile-card-directory-listing)
  - [x] Verify the card resembles this type of data structure: https://fas.yale.edu/fas-governance/fas-deans-office

- [x] Navigate to the [Profile Card Component Story](https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--profile-card)
  - [x] Verify the card has Storybook control options and you can switch between `grid`, `list`, and `condensed` (see examples in video below)
  - [x] Verify the `list` and `condensed` displays resemble the designs: https://www.figma.com/proto/G4sJ0BLu4jCJpGzW82JHE8/YaleSites-Components?type=design&node-id=8416-27552&scaling=min-zoom&page-id=8239%3A26166
  - [x] Note: to make the images smaller than other `reference` cards, I had to add an optional and contextual `data-collection-source` attribute. In Storybook, this gets picked up because we define the variable in each collection page example. In Drupal, we simply need to pass this variable to any profile list component - `card_example_type: 'profile'`

- [x] Navigate to the [Post Card Component Story](https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--post-card&args=collectionType:condensed)
  - [x] Verify the card has Storybook control options and you can switch between `grid`, `list`, and `condensed` (see examples in video below)
  - [x]  Verify `condensed` resembles the design in Notion - https://www.notion.so/fourkitchens/News-Cards-Grids-Lists-827e9260ec3647fba279783c3e3b8649?pvs=4#7c29011257dc4cec9b3fe63bc12f874e

- [x] Navigate to the [Event Card Component Story](https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--event-card&args=collectionType:condensed)
  - [x] Verify the card has Storybook control options and you can switch between `grid`, `list`, and `condensed` (see examples in video below)
  - [x] Verify `condensed` resembles the design in Notion - https://www.notion.so/fourkitchens/Event-Lists-Cards-and-Grid-c185951ddf6842b38dba40da8efc2cff?pvs=4#bb151d3331d8476cae0d61ce972e2e8f

##### Card Collections
- [x] Navigate to the [Post Card Collection component Story](https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/organisms-card-collection--post-card-collection&args=collectionType:condensed)
  - [x] Verify the new `condensed` display mode renders

- [x] Navigate to the [Event Card Collection component Story](https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/organisms-card-collection--event-card-collection&args=collectionType:condensed)
  - [x] Verify the new `condensed` display mode renders
 
- [x] Navigate to the [Profile Card Collection component Story](https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/organisms-card-collection--profile-card-collection&args=collectionType:condensed)
  - [x] Verify the new `condensed` display mode renders

- [x] Navigate to the [Profile Directory Card Collection component story](https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/organisms-card-collection--directory-listing-card-collection&args=featured:false;heading:Person+Namerton)
  - [x] Verify the card resembles this type of data structure: https://fas.yale.edu/fas-governance/fas-deans-office
  - [x] Verify toggling between `featured` and non, the grid changes between 4-columns and 6-columns https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/organisms-card-collection--directory-listing-card-collection

### Video example | cards and card collections: 

https://github.com/yalesites-org/component-library-twig/assets/366413/15a66438-3d4a-435b-9673-bf2d9cb31eee

### Design Review
- [x] Verify the designs match the [Figma Designs](https://www.figma.com/proto/G4sJ0BLu4jCJpGzW82JHE8/YaleSites-Components?type=design&node-id=8239-26166&t=tPPrKP3gmj8tU8EI-0&scaling=min-zoom&page-id=8239%3A26166) and here: https://www.figma.com/proto/G4sJ0BLu4jCJpGzW82JHE8/YaleSites-Components?type=design&node-id=8416-27552&scaling=min-zoom&page-id=8239%3A26166 and Notion designs for `condensed` [event](https://www.notion.so/fourkitchens/Event-Lists-Cards-and-Grid-c185951ddf6842b38dba40da8efc2cff?pvs=4#bb151d3331d8476cae0d61ce972e2e8f), [post](https://www.notion.so/fourkitchens/News-Cards-Grids-Lists-827e9260ec3647fba279783c3e3b8649#fa2d4c3c3aec4a0ca357924da2795ddc)

### Accessibility Review
- [x] Verify the component meets Accessibility requirements

### CODE REVIEW

**Review by codechefmarc — CHANGES_REQUESTED** [review]
Most of these are working as intended. A few comments:
1. For the profile meta, if I just view the component itself and make the screen size around 1005, there is no padding on the "Professional Title", so it runs into the image. When viewed as part of the profile page itself, I don't see this happening at all. See screenshots:

Screenshot 2023-07-11 at 9 15 17 AM

Screenshot 2023-07-11 at 9 17 52 AM

2. For the profile card directory listing, on the existing site, the email address is clickable. I see on the profile page that the email address has the spiffy JS copy link, so that's good. But for the card, it doesn't have this or is clickable. Not sure if that is something we want to add or leave off. Personally, I say leave it off, but wanted to make a note of it.
3. For event condensed card, I'm not seeing the "Online" or "In person" as it shows on the design.
4. Designs for profile full display show the breadcrumbs above the meta profile component. Storybook has the breadcrumbs below the meta component. Not sure if this was changed at some point or not.
5. Also, same area - the person's name should not be in the normal title area as it is in Storybook as it shows up in the meta component already. Designs reflect this.

**Comment by joetower** [comment]
@codechefmarc Thank you for the thorough testing and feedback :partying_face: 

I pushed the following fixes: 

> For the profile meta, if I just view the component itself and make the screen size around 1005, there is no padding on the "Professional Title", so it runs into the image. When viewed as part of the profile page itself, I don't see this happening at all.

I added a `gap` between the elements, so this should no longer be an issue. 

- https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/molecules-meta--profile
- https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/page-examples-profiles--profile-page

Screenshot-20230711143118-1113x521

---

> For the profile card directory listing, on the existing site, the email address is clickable. I see on the profile page that the email address has the spiffy JS copy link, so that's good. But for the card, it doesn't have this or is clickable. Not sure if that is something we want to add or leave off. Personally, I say leave it off, but wanted to make a note of it.

Agreed. I think we should leave it off for now. 

---

> For event condensed card, I'm not seeing the "Online" or "In person" as it shows on the design.

Great catch! I totally missed its inclusion in the design. It should be there now:

https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--event-card&args=collectionType:condensed

Screenshot-20230711144029-1089x372

---

> Designs for profile full display show the breadcrumbs above the meta profile component. Storybook has the breadcrumbs below the meta component. Not sure if this was changed at some point or not.

and

> Also, same area - the person's name should not be in the normal title area as it is in Storybook as it shows up in the meta component already. Designs reflect this.


I moved the breadcrumbs above in the storybook page and removed the duplicate title: 

https://deploy-preview-263--dev-component-library-twig.netlify.app/?path=/story/page-examples-profiles--profile-page

Screenshot-20230711144832-1953x1126

**Review by codechefmarc — APPROVED** [review]
Nice! Tested these and they are all looking good to me. One small thought, for the profile page I see that the left side has a margin top to it so the text doesn't align up with the sidebar. See screenshot. In the design, it is this way - there is a little bit of margin above that text on the left side, so I'm still approving this but wanted to let you know if that was something we wanted to change.

Screenshot 2023-07-11 at 2 20 53 PM

**Comment by joetower** [comment]
@codechefmarc I like that thought, Marc. Being that Ashley designed it that way, I feel as though we should leave it as-is for now. I am questioning the top margin, though. It appears to be [coming from browser default styles](https://www.w3schools.com/cssref/css_default_values.php) = `1em`.

**Comment by joetower** [comment]
@dblanken Would you like to give this PR a look, as well?

**Review by dblanken-yale — APPROVED** [review]
Very nice to see all of this!  Thanks for including me.  Looks and functions great and matches designs very well.

**Pull request merged**
