### PR TITLE
YALB-980 - Alignment Part 2 -  Demo Pages in Storybook | YALB-995 - Left Aligned Components

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- Adds page layout to illustrate alignment options
- Components full-width: https://deploy-preview-203--dev-component-library-twig.netlify.app/?path=/story/page-examples-standard-pages--with-banner
- Component full-width, left-aligned (limited inner width): https://deploy-preview-203--dev-component-library-twig.netlify.app/?path=/story/page-examples-standard-pages--with-banner-left-align
- This branch pulls in the latest tokens release which changes the `max` width token to `1600px` and changes the token variable name of what was `feature` width to now be `site` width
- This branch maps the `site` width to components/layouts which previously used `max` width
- `max` width is now used for components which should render wider than our site width of `1344px`, such as: 
  - banner
  - grand hero
  - media galleries
 
### Testing Link(s)
- [ ] Navigate to the [Component Page Banner Full-Width Story](https://deploy-preview-203--dev-component-library-twig.netlify.app/?path=/story/page-examples-standard-pages--with-banner)
- [ ] Navigate to the [Component Page Banner Full-Width Left-Align Story](https://deploy-preview-203--dev-component-library-twig.netlify.app/?path=/story/page-examples-standard-pages--with-banner-left-align)

### Functional Review Steps
- [ ] Review Standard Page With Banner demo page in Storybook
- [ ] https://deploy-preview-203--dev-component-library-twig.netlify.app/iframe.html?args=&id=page-examples-standard-pages--with-banner
- [ ] Inspect the text components, note that the text content is `center` aligned with a width of `content`
- [ ] Review Standard Page With Banner Left Aligned demo page in Storybook
- [ ] https://deploy-preview-203--dev-component-library-twig.netlify.app/iframe.html?args=&id=page-examples-standard-pages--with-banner-left-align
- [ ] Inspect the text components, note that the text content is `left` aligned with a width of `max`
- [ ] Note that the `video` and `image` components are `center` aligned with a width of `content`
- [ ] Note that the `tabs` component is `center` aligned with a width of `site`
- [ ] View the Banner in isolation and test each variation https://deploy-preview-203--dev-component-library-twig.netlify.app/?path=/story/molecules-banners--action-banner
yalb-action-banner

- [ ] And the Grand Hero  - testing each variation: https://deploy-preview-203--dev-component-library-twig.netlify.app/?path=/story/molecules-banners--grand-hero-banner
yalb-grand-hero

- [ ] Verify that the site header is `1344px` wide still. If you inspect it, note that its width is set to `site` instead of `max`

yalb-site-header-footer

### CODE REVIEW

**Comment by ahitson** [comment]
- [on this page](https://deploy-preview-203--dev-component-library-twig.netlify.app/?path=/story/page-examples-standard-pages--with-banner) the cards are not going to site width

Banner left align page:
- the top banner has the text too far inside the banner, should be more left. As the screen expands, it should stay offset to the left instead of scooting inside the page margins. The bottom version also isn't lining up with the page text.
- the breadcrumbs and title don't line up
- the cards need to go to site width
- the accordion isn't working, but maybe it's fine?
- let's start with these changes.

Screen Shot 2023-03-01 at 10 22 23 AM
Screen Shot 2023-03-01 at 10 27 46 AM

**Comment by joetower** [comment]
@ahitson ah, I'm sorry! I totally forgot about Netlify and its caching. I cleared the cache and rebuilt the branch environment. If you take another look at the test URLs, things should look better now.

**Comment by ahitson** [comment]
Yes, that cleared some things up. 
- On the Grand hero contained banner, the text is still going too far into the banner on smaller sizes and extending too far outside the banner on larger sizes. 
- For the action banner, the size of the right/left overlay changes when expanded. Let's keep it at the smaller size.
- Thinking we should keep the cards at site width to keep everything more in line. 

Screen Shot 2023-03-01 at 12 49 10 PM
Screen Shot 2023-03-01 at 12 49 26 PM
Screen Shot 2023-03-01 at 12 56 07 PM
Screen Shot 2023-03-01 at 12 56 13 PM

**Comment by joetower** [comment]
@ahitson The Grand Hero content should now align with the banner content. Please let me know if the content box width being `content` width looks good. 

I changed the `card-collection` component to use `site` width regardless of `list` or `grid` presentation. 
- https://deploy-preview-203--dev-component-library-twig.netlify.app/?path=/story/page-examples-standard-pages--with-banner
- https://deploy-preview-203--dev-component-library-twig.netlify.app/?path=/story/page-examples-standard-pages--with-banner-left-align

**Comment by ahitson** [comment]
Other than the line length of the text boxes being so long (out of our hands), this looks great. Thanks!

**Review by ahitson — APPROVED** [review]

**Review by kara-franco — APPROVED** [review]
Looks great! I tested using browser zoom and none of the alignment changes disrupted the content flow. Nice work!

**Pull request merged**
