### PR TITLE
fix(yalb-1104): alignment fixes part 2

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- fixes for component alignment
- bug fixes for Safari
- Fixes outlined here: https://yaleedu.sharepoint.com/:w:/r/sites/YaleSitesUpgradeProgram/_layouts/15/Doc.aspx?sourcedoc=%7B182C4A7D-F583-4C01-84EA-79411D3F7ED3%7D&file=YALB-1055%20Aligning%20components.docx&_DSL=1&action=default&mobileredirect=true&cid=b205c12a-8abf-4800-9800-b238f5fe1c93

--- 

### Testing Link(s)
- Fix: search input width fix - increased width, kept padding: https://deploy-preview-222--dev-component-library-twig.netlify.app/?path=/story/page-examples-standard-pages--basic&args=utilityNavSearch:true
- Fix: options on site header component: https://deploy-preview-222--dev-component-library-twig.netlify.app/?path=/story/organisms-site-header--header 

---
### Functional Review Steps
- [ ]  Fix: search input width fix - increased width, kept padding: https://deploy-preview-222--dev-component-library-twig.netlify.app/?path=/story/page-examples-standard-pages--basic&args=utilityNavSearch:true
  - [ ] Verify the input text does not get ever so slightly cut off in Chrome 
  -  Screenshot-20230413094149-468x255
  - [ ] Verify the search icon and input are aligned on mobile - like this: 
  - Screenshot-20230413094439-749x713
---

- [ ] Fix: options on site header component: https://deploy-preview-222--dev-component-library-twig.netlify.app/?path=/story/organisms-site-header--header 
  - [ ] Verify that only `left`, `center`, and `right` are alignment options. 
  - https://user-images.githubusercontent.com/366413/231797768-de008983-4286-4a01-811b-d1539b42ebfb.mp4

---

- [ ] Fix: text with image / content spotlight: if last component on page, no bottom border: https://deploy-preview-222--dev-component-library-twig.netlify.app/?path=/story/page-examples-standard-pages--basic&args=utilityNavSearch:true 
  - [ ] Verify the last text-with-image component does not have a bottom border
  - 
Screenshot-20230413094945-1545x675

---

- [ ] Fix: margin-top on `h2`, `h3`, `h4`, `h5`, `h6` : https://deploy-preview-222--dev-component-library-twig.netlify.app/?path=/story/page-examples-standard-pages--basic&args=utilityNavSearch:true
- [ ] Verify `h` elements have more top margin than they did
- https://user-images.githubusercontent.com/366413/231798669-22549591-9d19-4224-91ec-30a2d203c16e.mp4

---

- [ ] Fix: footer spacing - increase footer spacing
   - [ ] verify that there is now `var(--size-spacing-13))` between the last component on the page and the footer.
   - https://user-images.githubusercontent.com/366413/231799291-a1ee1511-cd14-4fe7-8621-1cd5848cdcdc.mp4
---
## [YALB-1109: bug: custom cards do not have correct styling](https://yaleits.atlassian.net/browse/YALB-1109)
- [ ] Fix: custom card collection alignment
- [ ] Navigate to: https://deploy-preview-222--dev-component-library-twig.netlify.app/?path=/story/organisms-card-collection-custom-card-collection--custom-card-collection
- [ ] Mark both `images` and `featured` as `false`
  - Screenshot-20230413100516-1152x1177
- [ ] Using the web inspector, add some extra content to some of the cards - leaving some with little content.
  - https://user-images.githubusercontent.com/366413/231803431-9016f8ac-9f79-44c4-abaf-a1a774ef525c.mp4
- [ ] Now, in the web inspector, again, delete one of the items and verify the cards stat the same size
- https://user-images.githubusercontent.com/366413/231803618-a6b93fbf-ecfd-4302-a520-9af3c8a3d294.mp4
- In the jira ticket, the reported issue appears to have been caused by non-breaking spaces in the WYSIWYG. Rather, the `content` repeating was rendering as one long run-on word. I was unable to reproduce the issue, locally, in Drupal. 

---
## [YALB-1111: Bug: Safari images/cards](https://yaleits.atlassian.net/browse/YALB-1111)
- [ ] Fix: image height in Safari
  - [ ] Using Safari, navigate to https://deploy-preview-222--dev-component-library-twig.netlify.app/?path=/story/organisms-card-collection--news-card-collection
  - [ ] Verify the images in the card collections render as they should and do not appear skewed/distorted
  - [ ] Try each variation - `grid`, `list`
Screen Shot 2023-04-13 at 10 23 52 AM

### CODE REVIEW

**Comment by ahitson** [comment]
Custom Cards:
- The cards are missing the light grey outline.
- The custom cards without images are missing their grow animation on the color bar. We should also tie these bars to color themes. So the long part is slot 1 and the short line is slot 3. (Check out the line on the bottom of [this](https://www.figma.com/proto/G4sJ0BLu4jCJpGzW82JHE8/YaleSites-Components?node-id=5762-18918&scaling=min-zoom&page-id=5219%3A23802) on hover)
- Also, on small breakpoints the cards should go 2 across and on x-small they are 1 across.

Some new bugs that popped up (with images below):
- The subhead on Content Spotlights lost its padding.
- The news/events card collection with images has new padding between the image and text. 
- The gallery component has a heading much closer than other components (custom cards for comparison)

Screen Shot 2023-04-13 at 1 49 25 PM
Screen Shot 2023-04-13 at 1 50 28 PM
Screen Shot 2023-04-13 at 1 51 53 PM
Screen Shot 2023-04-13 at 1 51 59 PM


Note for the future: we might have to just have a display option on the Content Spotlight that says "hide bottom border" for situations when it's next to a component like the Callout.

**Comment by joetower** [comment]
@ahitson Thank you!

For these feedback items:

Custom Cards:

- The cards are missing the light grey outline.
- The custom cards without images are missing their grow animation on the color bar. We should also tie these bars to color themes. So the long part is slot 1 and the short line is slot 3. (Check out the line on the bottom of [this](https://www.figma.com/proto/G4sJ0BLu4jCJpGzW82JHE8/YaleSites-Components?node-id=5762-18918&scaling=min-zoom&page-id=5219%3A23802) on hover)

Can we please create a separate ticket to address these? I'd rather keep this branch/ticket focused on fixes. 

---

For this feedback: 
-  Also, on small breakpoints the cards should go 2 across and on x-small they are 1 across.

I didn't make any changes which would have affected this. Which cards should be 2 up at `x-small` sizes? The ones without images? Featured or non-featured? At what breakpoint should they switch to 1 up?

---

For these, I'll add some follow-up comments: 

- The subhead on Content Spotlights lost its padding.
  - I'll look into this. I didn't make a change which should have affected this. 
- The news/events card collection with images has new padding between the image and text.
  - Is it possible this happened while you were resizing the browser window? If so, could you test the breakpoint by refreshing the page while at that breakpoint?
- The gallery component has a heading much closer than other components (custom cards for comparison)
  - On which page are you seeing this issue? Could you provide more details?

**Comment by ahitson** [comment]
We can leave the breakpoints alone for now and I'll make that card ticket. 

For the news cards, they are just appearing like that on page load, no resizing needed.

**Comment by ahitson** [comment]
Looks good!

**Review by ahitson — APPROVED** [review]

**Review by nJim — APPROVED** [review]
Approved

**Pull request merged**
