### PR TITLE
YALB-526: Table styles

### PR DESCRIPTION
**Pull request by ModulesUnraveled**
### Description of work
- Styles raw tables (that would be created by the wysiwyg

### Testing Link(s)
- [ ] Navigate to the [Component Story](https://deploy-preview-XX--dev-component-library-twig.netlify.app/?path=/story/atoms-table--table)

### Functional Review Steps
- [ ] Verify you can install the component with the CLI

### Design Review
- [ ] Verify the designs match the [Figma Designs](https://www.figma.com/file/OVfmCW5s1gI7xnrM8ibX2y/UI-Kit-Alpha-%5BYaleSites%5D)
- [ ] Review any new [Percy builds](https://percy.io/95144ff9/component-library-twig)

### Accessibility Review
- [ ] Verify the component meets Accessibility requirements

### CODE REVIEW

**Review by ntay90 — CHANGES_REQUESTED** [review]
Can we add a `scope="col"` to the column headers and `scope="row"` to the row headers? 

- [ ] Add a `scope="col"` and `scope="row"` to the respective `<th>` tags.

**Comment by ModulesUnraveled** [comment]
@ntay90 unfortunately no, this is a straight copy and paste of the markup Drupal creates in the wysiwyg. This ticket is simply applying css to that markup. If we wanted to affect the markup, we'd probably need to look into contrib modules or custom coding - which want a party of the scope of this ticket

**Comment by ModulesUnraveled** [comment]
@ntay90 Per Megan's [comment in Jira](https://yaleits.atlassian.net/browse/YALB-526?focusedCommentId=91836) the markup is going to have to be handled in a separate ticket.

**Comment by ModulesUnraveled** [comment]
I'm going to merge this, since it's only affecting styles, and Ashley isn't here to review it. We'll make sure she does when she's back from vacation. But in order to not hold things up this sprint, we're pushing it through.

**Pull request merged**
