### PR TITLE
YALB-796-Feedback: Text with Image breakpoints

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- Adds offset/alignment styles for small bp `content` and `focus` variations

### Testing Link(s)
- [ ] Navigate to the [Component Story](https://deploy-preview-178--dev-component-library-twig.netlify.app/?path=/story/molecules-text-with-image--text-with-image&args=position:image-right)

### Functional Review Steps
- [ ] At the “Medium” breakpoint…
  - [ ] For an “Image Focus” variation of the component
    - [ ] The image and text stack with the image on the top.
    - [ ] For the “Image Left” variation… the image is left aligned on the page and has a gap on the right side. The text has the same gap on the left side.
    - [ ] For the “Image Right” variation… the image is right aligned on the page and has a gap on the left size. The text has the same gap on the right side.
    - [ ] These rules apply to both the “Feature” and “Highlight” variations of the component.
  - [ ] For the “Equal Focus” variation of the component
    - [ ] The image and text appear side by side 50-50.
  - [ ] For the “Text Focus” variation of the component
    - [ ] The image and text appear side by side (I’m not sure of the ratio, but the image is smaller)
    
yalb-796-medium

    
---
- [ ] For the “Small” breakpoint…
  - [ ] The size of the image is dictated by the focus.
  - [ ] “Image Focus” has a full width image
  - [ ] “Equal Focus” is smaller (possibly 75%?)
  - [ ] “Text Focus” is even smaller (possibly 50%?)
  - [ ] The image is aligned to the right or left based on named variation.
  - [ ]  The text follows similar gap-rules as described in the medium breakpoint. Check out figma for more detail.
  
yalb-796-small

### Design Review
- [ ] Verify the designs match the [Figma Designs](https://www.figma.com/file/G4sJ0BLu4jCJpGzW82JHE8/YaleSites-Components?node-id=5216%3A22268&t=pdf27hra6AxBcmRL-0)
- [ ] Review any new [Percy builds](https://percy.io/95144ff9/component-library-twig)

### CODE REVIEW

**Comment by ahitson** [comment]
In the xs thru small range, the images should scale (image focus at browser width, equal at 75%, and content at 50%)

In the medium range, the image focus image wouldn't hit browser width yet, try widths of 85% image focus, 75% equal, 50% content. Initially, I had wanted the medium range equal and content focus to remain side-by-side, but let's skip it for now.

When the image is set to the right and the text on the left, there should be padding on the right of the text so it doesn't span across the screen at medium and small ranges (equal to the left text padding when the image is set to the left).

**Comment by joetower** [comment]
@ahitson Is this more in line with what you're thinking? 
https://deploy-preview-178--dev-component-library-twig.netlify.app/?path=/story/molecules-text-with-image--text-with-image&args=position:image-right

- The text/image stagger now applies from a resolution of `0` wide to the `large` (992px) breakpoint. When the image is right-aligned, the text gets a max-width of `75%` at both `equal` and `content` focus states. 

- When the focus is set to `image`, the image will render at `85%` of the browser width until the `large` (992px) breakpoint. It is following the same responsiveness as the `equal` and `content` focus states. If you would like the image to render `100%` at the `medium` breakpoint, instead, please let me know.

**Comment by ahitson** [comment]
Only have changes to the image focus states. It only has the image only on the left, but it needs to flip to the other side when right is selected. Also, the text on image focus should be shifted to the right when the image is on the left like on the other focus states.

**Review by ahitson — APPROVED** [review]

**Comment by joetower** [comment]
@callinmullaney :wave: Heya, when you have time, could you please give this a code review? Ashley has approved it from a design perspective.

**Review by callinmullaney — APPROVED** [review]
@joetower Looks good on my end. One thing I want to mention here that you might want to refactor before merging or follow up with a separate task; It's seems that the authoring style for the rest of the components is element -> data-attribute -> media query. This was originally done so the style sheet doesn't have duplicate selectors. For example, the changes here have 3 instances of `[data-collection-type='grid'][data-collection-featured='false']`. But I did find a couple files while looking through that are doing element -> media query -> data-attribute. _yds-reference-card.scss for example.

Not sure if this is a blocker for launch but it is an inconsistency with the authoring style I noticed.

**Comment by joetower** [comment]
> @joetower Looks good on my end. One thing I want to mention here that you might want to refactor before merging or follow up with a separate task; It's seems that the authoring style for the rest of the components is element -> data-attribute -> media query. This was originally done so the style sheet doesn't have duplicate selectors. For example, the changes here have 3 instances of `[data-collection-type='grid'][data-collection-featured='false']`. But I did find a couple files while looking through that are doing element -> media query -> data-attribute. _yds-reference-card.scss for example.
> 
> Not sure if this is a blocker for launch but it is an inconsistency with the authoring style I noticed.

@callinmullaney I adjusted this. Could you please take a look and confirm that I understood what you were outlining? That's good to know about that authoring style. Thank you!

**Comment by joetower** [comment]
@ahitson When you have a chance could you please look at the Percy tests? We'll talk about removing Percy or making some kind of config change. Thank you.

**Comment by ahitson** [comment]
Think I got the ones related to this. And, yes, let's talk about it.

**Review by callinmullaney — APPROVED** [review]
@joetower The changes and refactor look good to me. I say :shipit:

**Comment by nJim** [comment]
Marking this a 'dont merge' as Yale is considering changes to these design decisions. Ashely is working with Franz and April to determine next steps.

**Comment by joetower** [comment]
@ahitson Please take a look at the text with image example page I set up and let me know if you want to adjust/change anything.
 
 https://deploy-preview-178--dev-component-library-twig.netlify.app/?path=/story/page-examples-standard-pages--with-text-with-image&args=imageWidth1:feature;imagePosition1:image-left;imageFocus1:content;imageWidth2:highlight;imagePosition2:image-right;imageFocus2:equal

**Comment by ahitson** [comment]
@joetower Can we start with an image at feature width with an intro paragraph underneath, followed by a **featured** card grid, then the 2 text with images, then the event list?

Is it possible to change the content in these components so they're not repetitive?

**Comment by joetower** [comment]
@ahitson How does this look? 
https://deploy-preview-178--dev-component-library-twig.netlify.app/?path=/story/page-examples-standard-pages--with-text-with-image

**Comment by joetower** [comment]
@ahitson Awesome! How about this? 
https://deploy-preview-178--dev-component-library-twig.netlify.app/?path=/story/page-examples-standard-pages--with-text-with-image

**Comment by ahitson** [comment]
Yes! Thank you! 

However, now that we get to see them together, I see a problem. No matter the focus the text should have the same gaps on the left and right. Right now, the image focus has smaller padding to the text underneath than the other focus states do. The text boxes should be the same size on all focuses once it stacks.

Frame 466

**Comment by ahitson** [comment]
When it first stacks at medium, the image-focused version with image on the left has text with less padding on the left than the other versions.

**Comment by joetower** [comment]
@ahitson Ah, yes! I see the issue. I pushed up a fix, could you please give this another look and test with all the variations?

**Comment by joetower** [comment]
@ahitson The new `spacing-page-section-spacious` rule is ready for review here: https://deploy-preview-178--dev-component-library-twig.netlify.app/?path=/story/page-examples-standard-pages--with-text-with-image

Because I have the hero banner video component updates in PR review as well, are you okay if we make the `spacious` changes to `banners`, `callouts`, and `quicklinks` in a separate follow up ticket? I'd like to avoid any conflicts and also keep this PR specific to this component.

**Comment by ahitson** [comment]
Thank you!!!!

**Pull request closed without merging**
