### PR TITLE
YSP-646: PRESIDENT: Event time display updates

### PR DESCRIPTION
**Pull request by chaohlu**
### Description of work
- Remote spaces
- Replace am to a.m. and pm to p.m.

### Testing Link(s)
- [ ] Navigate to the [Event Story](https://deploy-preview-405--dev-component-library-twig.netlify.app/?path=/story/molecules-meta--event&args=allDay:false)
- [ ] Navigate to the [Localist Event Story](https://deploy-preview-405--dev-component-library-twig.netlify.app/?path=/story/molecules-meta--event-localist)

### Functional Review Steps
- [ ] Verify that times are of the form "x:xx A.M." or "x:xx P.M." 
- [ ] Verify dashes are actually emdashes
- [ ] Verify other variations of the date and time formatting where you can (all day, changing times, changing days)
- [ ] Verity style/format

### Accessibility Review
- [ ] Verify the component meets Accessibility requirements

### CODE REVIEW

**Review by kara-franco — CHANGES_REQUESTED** [review]
Nice work! I think the only small tweak needed is to replace the dash with an emdash. Em dash (—) &mdash;

**Comment by dblanken-yale** [comment]
Yep I'll try to make that change as well.

**Comment by dblanken-yale** [comment]
@kara-franco Ok it's out there; let me know if I missed any but I think I got them all.

**Review by atiddei — APPROVED** [review]
This looks good but maybe a future update for the localist view with the image on the right the time breaking to a new line.

**Comment by dblanken-yale** [comment]
@atiddei Mind making a ticket for that one; that's one thing @chaohlu noticed also.  I bet if we surrounded that in some markup we could make that happen.

**Review by dblanken-yale — APPROVED** [review]

**Review by kara-franco — APPROVED** [review]

**Pull request merged**
