### PR TITLE
YALB-887 - Feedback: Animated underline still not there

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- fix: add text-shadow to links with animated underline
- add new link style for `no-animation` which doesn't include the underline effects

### Testing Link(s)
- [ ] testing environment: https://deploy-preview-188--dev-component-library-twig.netlify.app

### Functional Review Steps
- [x] Navigate to components which use the animated underline:
  - [x] https://deploy-preview-188--dev-component-library-twig.netlify.app/?path=/story/atoms-controls--text-link
  - [x] https://deploy-preview-188--dev-component-library-twig.netlify.app/?path=/story/molecules-alert--alert-examples
  - [x] https://deploy-preview-188--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--custom-card&args=heading:This+is+a+long+link+join+us
  - [x] https://deploy-preview-188--dev-component-library-twig.netlify.app/?path=/story/molecules-search-result--search-result
  - [x] https://deploy-preview-188--dev-component-library-twig.netlify.app/?path=/story/molecules-tabs--tabs (text content links)
  - [x] https://deploy-preview-188--dev-component-library-twig.netlify.app/?path=/story/molecules-text--text-field (text content links)
- [x] Navigate to view the new `no-underline-animation` text-link variation: http://localhost:6006/?path=/story/atoms-controls--text-link 
  - [x]  Which is used in a component like the Grand Hero (and for any future component which places text-links on top of imagery) https://deploy-preview-188--dev-component-library-twig.netlify.app/?path=/story/molecules-banners--grand-hero-banner&args=linkContent:This+is+a+long+link+join+us and verify the Grand Hero component does not have an animated underline

### CODE REVIEW

**Comment by ahitson** [comment]
2 small things. 
- On the alert banner the underline is getting pushed up under the baseline, so it's halfway behind the text.
- The Grand Hero should have a chevron link >

**Comment by joetower** [comment]
@ahitson Thank you! I'll take a look at the alert banner instance. :+1: 

For the Grand Hero, we must have missed adding the chevron in the component ticket or we had a regression? On production I'm not seeing a chevron either :thinking: https://yalesites-org.github.io/component-library-twig/?path=/story/molecules-banners--grand-hero-banner

Is there another link example somewhere that uses the chevron?

**Comment by ahitson** [comment]
It appears that is the only component that uses it, so let's skip the chevron for now and ignore what I said.
Alerts are good now!

**Review by ahitson — APPROVED** [review]

**Comment by joetower** [comment]
@ahitson Awesome! Thank you!

**Review by mariannuar — APPROVED** [review]
@joetower Code looks good and it works great!

**Pull request merged**
