### PR TITLE
YSP-496: Increase Site Name Image width

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- Updates the site-name-as-logo width to 400px to accommodate longer site names/logos
- Updates the example svg 

### Testing Link(s)
- [ ] Navigate to the [Component Story](https://deploy-preview-361--dev-component-library-twig.netlify.app/?path=/story/organisms-site-header--header)
- [ ] https://pr-640-yalesites-platform.pantheonsite.io/

### Functional Review Steps
- [ ] navigate to: https://deploy-preview-361--dev-component-library-twig.netlify.app/?path=/story/organisms-site-header--header
- [ ] You can also test in Drupal here: https://pr-640-yalesites-platform.pantheonsite.io/
- [ ] Toggle the Site Name is Logo
- [ ] Inspect the SVG and note it is now 400px wide
- [ ] Note that the typical image aspect ratio would likely be 400px wide by 100px high (or less ~ 80px). I have made the maximum height 200px, set in rem values. So the total max image size is `400px` wide by `200px` high.

https://github.com/yalesites-org/component-library-twig/assets/366413/fa89208e-5826-49d7-bebc-a6629a4ec088

### CODE REVIEW

**Review by codechefmarc — APPROVED** [review]
Looks good to me! Approved.

**Comment by dblanken-yale** [comment]
I'm seeing some strange behavior from the Drupal end of this.  Here is the same page in both Safari and Chrome:

Chrome Desktop:
Screenshot 2024-04-26 at 11 22 46 AM

Chrome Mobile:
Screenshot 2024-04-26 at 11 23 03 AM

Safari Desktop:
Screenshot 2024-04-26 at 11 22 55 AM

Safari Mobile:
Screenshot 2024-04-26 at 11 23 31 AM

Are you seeing similar?

**Comment by joetower** [comment]
@dblanken-yale Yes, I _think_ there is something weird with the specific svg uploaded. I was having similar issue locally, but if I used a different svg, everything was rendering fine.

**Review by dblanken-yale — APPROVED** [review]
Oh good.  Ya the changes looked great, but saw that and wondered.  Looks great!

**Review by kara-franco — APPROVED** [review]
Looks great to me!

**Review by miketullo95 — APPROVED** [review]
👍

**Pull request merged**
