### PR TITLE
YALB-1052: Feedback: H1 spacing

### PR DESCRIPTION
**Pull request by mariannuar**
### Description of work
- Add more space between heading and header for pages withouth breadcrumbs

### Functional Review Steps in Preview
- [x] Navigate to the [Page Example Story](https://deploy-preview-214--dev-component-library-twig.netlify.app/?path=/story/page-examples-events--event-page) with controls to hide the breadcrumbs
- [x] Confirm the space between the header, breadcrumbs and page title is still the same.
- [x] Hide the breadcrumbs, and confirm there is a space of `2rem` between the header and the heading.

### Functional Review Steps in Local
- [x] To test this for pages without breadcrumbs, in your local run `npm run local:review-with-cl-branch YALB-1052--h1-spacing-fix` to review with the changes from this branch
- [x] Visit the site and go to any page without breadcrumbs. For example: https://yalesites-platform.lndo.site/faqs
- [x] Confirm there is a space of `2rem` between the header and the heading.
- [x] Now visit a page with breadcrumbs, for example: https://yalesites-platform.lndo.site/top-goal-site/asdasdasd
- [x] And confirm the space still looks good

### CODE REVIEW

**Comment by mariannuar** [comment]
@ahitson Fixed! Let me know if that way works :) thanks!

**Comment by ahitson** [comment]
Woo! Ok, now we just need to add breakpoints logic so it's not too far on smaller screens:
at Large:  --size-spacing-8
at Small:  --size-spacing-7

**Comment by ahitson** [comment]
🎉

**Review by ahitson — APPROVED** [review]

**Review by joetower — APPROVED** [review]
@mariannuar This looks great! Great work, thank you! 

:shipit:

**Pull request merged**
