### PR TITLE
YOR-11: Event Calendar Display Mode

### PR DESCRIPTION
**Pull request by dblanken-yale**
### Description of work
- Create and style the Calendar component in Storybook
- Add js functionality for the Modal events on the desktop
- Add js functionality for the Calendar weeks navigation on mobile
- Add js functionality for the active day events listing

### Testing Link(s)
- [ ] Navigate to the [Calendar Story](https://deploy-preview-424--dev-component-library-twig.netlify.app/?path=/story/organisms-calendar--calendar)

### Functional Review Steps
- [ ] Verify you can open the Modal when clicking on the "more events" link from the Calendar cell with more than one event.
- [ ] Verify you can navigate between weeks on mobile
- [ ] Verify you can see the events list for the active day when clicking the Calendar day date. The "No events" text should be displayed if the clicked day has no events.
- [ ] Verify responsiveness of the Calendar component styles and functionality. 

### Design Review
- [ ] Verify the designs match the [Figma Designs](https://www.figma.com/design/7dxhigoRGh80M0EOZ3wONc/Design?node-id=53-6417&t=TBRP3r4fqnqrmmep-4)

### Accessibility Review
- [ ] Verify the component meets Accessibility requirements

### CODE REVIEW

**Comment by miketullo95** [comment]
This looks great! I do think we need to make sure there is a ticket for the quick change Franz requested (changing the style of the numbers to the other number style). I'm not sure if thats making it in here, but lets not lose that info.

**Review by miketullo95 — APPROVED** [review]

**Comment by dblanken-yale** [comment]
@miketullo95 Take a look now; should have changed both the days that display on the overall calendar as well as the date title of the modal when you click into it.

**Comment by miketullo95** [comment]
> @miketullo95 Take a look now; should have changed both the days that display on the overall calendar as well as the date title of the modal when you click into it.

this looks fantastic! for future vendor work, maybe we can have a little blurb in docs somewhere about old/new nums usage. Approved and gtg for me!

**Review by chaohlu — APPROVED** [review]
Love the new styling and very responsive!

**Pull request merged**
