### PR TITLE
YALB-34: create quick links molecule

### PR DESCRIPTION
**Pull request by codeb-a**
### Description of work
- Creates Quick Links component.

### Testing Link(s)
- [ ] Navigate to the [Component Story](https://deploy-preview-123--dev-component-library-twig.netlify.app/?path=/story/tokens-breakpoints--breakpoints)

### Functional Review Steps
- [ ] Verify you can install the component with the CLI

### Design Review
- [ ] Verify the designs match the [Figma Designs](https://www.figma.com/file/OVfmCW5s1gI7xnrM8ibX2y/UI-Kit-Alpha-%5BYaleSites%5D)
- [ ] Review any new [Percy builds](https://percy.io/95144ff9/component-library-twig)

### Accessibility Review
- [ ] Verify the component meets Accessibility requirements

### CODE REVIEW

**Review by ModulesUnraveled — APPROVED** [review]
I think everything looks good to me... but I also wrote some of it... so, I'd love if @callinmullaney could glance over the code

**Review by ntay90 — CHANGES_REQUESTED** [review]
The list of links should probably be marked up as a semantic unordered list, if possible.

- [ ] Mark up links as a semantic unordered list.

Screen Shot 2022-09-01 at 10 57 32 AM

**Comment by ModulesUnraveled** [comment]
@ntay90 Ready for your re-review!

**Review by ntay90 — APPROVED** [review]

**Comment by ModulesUnraveled** [comment]
@codeb-a I think you can go ahead and merge this. Ashley will review it when she's back next week, so we can merge without the visreg review.

@callinmullaney if you want to take a look at this, please do! I just want to get this merged to unblock the wiring ticket.

**Pull request merged**
