### PR TITLE
YALB-531: Wiring Design Feedback

### PR DESCRIPTION
**Pull request by ModulesUnraveled**
### Description of work
- Updates the `spacing-page-section` mixin to support "flush-top" and "flush-bottom" variations
- Adds "mobile" and "desktop" versions of the `--spacing-page-section` property
- Defines paragraph spacing (rather than using browser defaults)
- Accordion:
	- Removes unnecessary top/bottom padding
	- Styles the "main" heading
	- Fixes hover styles for items, and expand/collapse all toggles
	- Fixes "extra" padding of nested components in Drupal

### Testing Link(s)
- [ ] Navigate to the [Example page with banner](https://deploy-preview-87--dev-component-library-twig.netlify.app/?path=/story/page-examples-standard-pages--with-banner)
- [ ] Navigate to the [Example page with banner](https://deploy-preview-87--dev-component-library-twig.netlify.app/?path=/story/page-examples-page-examples--accordion-page)

### Functional Review Steps
- [ ] On the Banner Page
	- [ ] Verify the banner has top and bottom margin.
		- [ ] Inspect the breadcrumbs, and delete the whole element (So that the banner is the first element inside the `<main>` element
		- [ ] Verify that the banner no longer has top margin.
	  - [ ] Verify the callout does not have bottom margin
		  - [ ] Add something below it (in dev tools, you can drag another element below it) and verify it has both top and bottom margin.
	  - [ ] Scale the browser to "mobile" size (below 992px) and verify the top/bottom margin on "section" components (like the banner, and callout) is smaller than it was on "desktop"
	  - [ ] Inspect a `<p>` and verify it has styles defined by out `_text.scss` file (rather than using browser defaults)
		  - [ ] Verify that the last `<p>` in a `<div class="text">` component has no bottom margin.
- [ ] On the accordion page:
	- [ ] Verify there's no padding top nor bottom on the main "accordion" component
	- [ ] Verify the heading (on the second accordion group) is styled to use our serif font (YaleNew)
	- [ ] Verify the expand/collapse all, as well as each item change to blue on hover

### Design Review
- [ ] Verify the designs match the [Figma Designs](https://www.figma.com/file/OVfmCW5s1gI7xnrM8ibX2y/UI-Kit-Alpha-%5BYaleSites%5D)
- [ ] Review any new [Percy builds](https://percy.io/95144ff9/component-library-twig)

### Accessibility Review
- [ ] Verify the component meets Accessibility requirements

### CODE REVIEW

**Comment by ahitson** [comment]
Please remove the top padding from the banner at all times so it comes up flush with the breadcrumbs.

**Review by kara-franco — APPROVED** [review]
Changes look great!

**Comment by ModulesUnraveled** [comment]
@ahitson I moved the breadcrumbs to the "header" region (instead of the "content" one) I think that's a better representation of how it'll work once we have things wired in Drupal. Let me know if that solved your concerns about the banner. If not, let's jump on a call to figure out a good solution.

**Comment by ahitson** [comment]
I think that looks much better. Thanks!

**Review by ahitson — APPROVED** [review]

**Review by miketullo95 — APPROVED** [review]

**Review by callinmullaney — APPROVED** [review]
@ModulesUnraveled The changes to `spacing-page-section` seem like a much cleaner solution. :shipit:

**Pull request merged**
