### PR TITLE
YSP-559: Upgrade Node Packages - Component Library

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- Updates node to v20
- Updates packages
- Upgrades Storybook to the latest version - 8
- Made ys_links work again
- Made args where appropriate to allow initial Storybook pages to load without error
- Note: upgrading styelint to a higher version will take some research around compatibility with prettier.
- `defaultValue` has been deprecated in Storybook in favor of an `args` key on the `default` export. In the future, we may want to consider refactoring components that have several variations defined in one `.stories` file to have separate files so each variation can have default `args` export specific to the variation.
- Fixed initial load of pages providing errors due to site branding URL not being defined
- Added linkpurpose in replacement of ys_links
- Fix mega footer content link colors for visited and unvisited

### Functional testing steps:
- [ ] Verify there are no glaring issues when navigating https://pr-679-yalesites-platform.pantheonsite.io/
- [ ] Verify there are no glaring issues when navigating the component library: https://deploy-preview-378--dev-component-library-twig.netlify.app/
- [ ] Verify link treatments in all blocks and configurations you can think of

### CODE REVIEW

**Review by codechefmarc — APPROVED** [review]
All comments are over in the main repo PR. Approved!

**Comment by vinmassaro** [comment]
@joetower I needed to update all referenced Github Actions to latest versions in our workflows, so I piggy-backed on this PR. Here are the changes I made:

- Removed unneeded alias to run semantic-release since it can be run directly with `npx`
- Updated all Github Actions to lastest versions

The test workflow is now failing when running stylelint: https://github.com/yalesites-org/component-library-twig/actions/runs/9665926446/job/26664447837?pr=378#step:5:18

**Review by dblanken-yale — APPROVED** [review]
Compiles fine for me!  I'm going to rebase my linkpurpose work on this going forward so the intent would be to focus on getting linkpurpose working with this vs ys_links.

I realize this was not an easy task to accomplish; VERY nice job!

**Comment by dblanken-yale** [comment]
Incorporating this into the Drupal 10.3 upgrade.  Closing this PR

**Pull request closed without merging**
