### PR TITLE
YSP-308 - Reference cards: Create components from Designs

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- Adds new `data-collection-type` type for `single` application
- Leverages `featured` and `non-featured` for the 2 style variations
- Applies styling depending on `data-collection-source` type. Adds specific styles for `profile` type, given the card content is less than an event or news source.

### Testing Link(s)
- [x] Navigate to the [Component Story](https://deploy-preview-345--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--post-card&args=collectionType:single)

### Functional Review Steps
- [ ] Navigate to the following examples (the urls with parameters may not work, if not change the collection type to `single` - see video screen capture below):
   - [ ] Post | Card | Featured: https://deploy-preview-345--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--post-card&args=collectionType:single
   - [ ] Post | Card | Non-Featured: https://deploy-preview-345--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--post-card&args=collectionType:single;featured:false
   - [ ] Event | Card | Featured: https://deploy-preview-345--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--event-card&args=collectionType:single
   - [ ] Event | Card | Non-Featured: https://deploy-preview-345--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--event-card&args=collectionType:single;featured:false
   - [ ] Profile | Card | Featured: https://deploy-preview-345--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--profile-card&args=collectionType:single
   - [ ] Profile | Card | Non-Featured:  https://deploy-preview-345--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--profile-card&args=collectionType:single;featured:false

https://github.com/yalesites-org/component-library-twig/assets/366413/4ec6dfff-3159-4b73-b1e3-17c2d3c156b8

### Design Review
- [ ] Verify the designs match the [Figma Designs](https://www.figma.com/proto/4Lx9A5sxO08DxUNbewalrR/Yale-Sites-ideation?type=design&node-id=1092-15&t=hNGyksjYwDFKHo1d-0&scaling=min-zoom&page-id=1092%3A2)

### Accessibility Review
- [ ] Verify the component meets Accessibility requirements

### CODE REVIEW

**Comment by dblanken-yale** [comment]
@joetower Nice work.  I had a question about the profile, but very minor and probably not blocking?  On the other cards, you're able to specify `Featured` as well as `With Image`, and if there is no image, it still features the display of the text on the right side for `single` collection type.  But with the profile, it does not do this and keeps the image.  Is this by design?

Post Card:
Screenshot 2024-03-22 at 8 54 41 AM

Profile Card:
Screenshot 2024-03-22 at 8 54 57 AM

**Review by codechefmarc — CHANGES_REQUESTED** [review]
Looks really good! Even though it wasn't part of the testing instructions, I did also test with/without images. The post and event card worked, but the profile card didn't - the image stayed in there even with it set to `false`. I assume that should work in the component library ahead of wiring to Drupal? Good work!

**Comment by joetower** [comment]
@dblanken-yale @codechefmarc Thank you both for thorough testing. 

It looks like the Profile reference cards never accounted for `With Image` to be set to `false` - regardless of collection type selected. I'll give this some thought and let you know when it's ready for another look.

**Comment by joetower** [comment]
@dblanken-yale @codechefmarc This is ready for another look, please. 

https://deploy-preview-345--dev-component-library-twig.netlify.app/?path=/story/molecules-cards--profile-card&args=collectionType:single;withImage:false

I added an attribute to reference card items to flag whether the card has an image or not `data-component-has-image`. This way we can make conditional style changes to an individual card.

You should now see the following when testing `profile` cards or any `single` card with/without an image. 👍 

Screenshot 2024-03-25 at 11 20 38 AM
Screenshot 2024-03-25 at 11 20 56 AM

**Review by codechefmarc — APPROVED** [review]
Looks great, tested with all of the cards. Approved!

**Comment by miketullo95** [comment]
this looks great!! 👍

**Review by kara-franco — APPROVED** [review]
I love these!! a11y approved (there is one contrast warning, but it's the same one that links flag, these are false positives). 

Beautiful work!

**Pull request merged**
