### PR TITLE
YALB-1581: Accessibility: Alert needs landmark and accessible name

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- wrap `alert` in a `<section>` instead of a `<div>`
- add `aria-label="announcement"` to the alert component
- add `aria-label` to the interactive media gallery caption toggle button
- adjust bottom-margin on wrapped-image component to match top-margin, decreasing the margin between the bottom of the floated image and the paragraph below it.

---

### Testing Link(s)
- [ ] Navigate to the [Component Story](https://deploy-preview-306--dev-component-library-twig.netlify.app/)

#### Testing: [YALB-1581: Accessibility: Alert needs landmark and accessible name](https://yaleits.atlassian.net/browse/YALB-1581)
- [x] Navigate to: https://deploy-preview-306--dev-component-library-twig.netlify.app/?path=/story/molecules-alert--alert
- [x] inspect the alert, verify it is a `<section>` element instead of a `<div>`
- [x] Verify it has and attribute of `aria-label="announcement"`

Screenshot 2023-10-11 at 2 02 42 PM

---

#### Testing: [YALB-1582: Accessibility: Media Gallery caption limit increase and expand button accessible name](https://yaleits.atlassian.net/browse/YALB-1582)
- [x] Navigate to: https://deploy-preview-306--dev-component-library-twig.netlify.app/?path=/story/organisms-galleries--interactive-grid
- [x] Verify the arrow toggle button has an `aria-label="expand"` attribute when the caption is collapsed, and `aria-label="collapse"` when it's expanded.

https://github.com/yalesites-org/component-library-twig/assets/366413/4771a011-8a8f-41da-8738-1cce0b506320

---
#### Testing: [YALB-1585: Spacing under caption of wrapped image block](https://yaleits.atlassian.net/browse/YALB-1585)
- [x] Navigate to: https://deploy-preview-306--dev-component-library-twig.netlify.app/?path=/story/molecules-wrapped-image--wrapped-image
- [x] Inspect the wrapped image, verify the spacing between the floated image and the paragraph under it has been decreased. Compare it to production: https://yalesites-org.github.io/component-library-twig/?path=/story/molecules-wrapped-image--wrapped-image

https://github.com/yalesites-org/component-library-twig/assets/366413/03b405f7-373c-490b-970d-0404187a0deb

---

### Accessibility Review
- [x] Verify the component meets Accessibility requirements

### CODE REVIEW

**Review by dblanken-yale — APPROVED** [review]
Functionally works great that I can see.  I did wonder what the _yds-tabs.scss changes do for what was tested; is there a spot I'm missing that re-uses these somehow?  Just wanted to make sure there wasn't something else we were supposed to test.

Great job as always!

**Comment by joetower** [comment]
@dblanken-yale Thank you! 😆 So, the tabs fix is something I noticed locally and added a fix for here. I didn't spell it out in testing. If you were to look at the mobile size of the tabs on this example page: https://dev-yalesites-sebastianna.pantheonsite.io/welcome/text-heavy-content, note how the bottom-border is visible on the active tab. 

Screenshot 2023-10-11 at 2 53 49 PM

If you were to test this locally, on this page https://yalesites-platform.lndo.site/testing-all-of-the-things you would now see this: 
Screenshot 2023-10-11 at 2 56 58 PM

The issue is that the tab_link height needs to be 100% so that the white border properly covers the `ul`s bottom border. Please let me know if you have any questions about this. 👍

**Review by myvaughn — APPROVED** [review]
The problem button in the modal now has an appropriate accessible name, either "expand" or "collapse" depending on the state. There seem to be other problems operating the gallery when I am testing with VoiceOver, but we'll save that for another ticket.

**Review by miketullo95 — APPROVED** [review]
wrapped image spacing looks great! 👍

**Comment by joetower** [comment]
@dblanken-yale I pushed up the change to the multi instance version of the galleries. Could you please give it a test? https://deploy-preview-306--dev-component-library-twig.netlify.app/?path=/story/organisms-galleries--interactive-grid

I met with Jim and he didn't have any recommendations on how we might go about this in a different way. He was all for moving forward with our approach.

**Comment by dblanken-yale** [comment]
@joetower Works great!  I'm still trying to compare the accordion since we should be having the same issue there, but I can't seem to find anything that would be different.  Our approach is similar without this change, but they each yield only one click event.  Puzzling!  I'm glad that Jim approves for now.  If I find anything more I'll let you know.

**Comment by dblanken-yale** [comment]
The accordion only runs the script once.  There has to be a place that's trying to call it more on the grid.  I just can't find it.

**Comment by joetower** [comment]
@dblanken-yale Sounds great, thank you! 

I am also spinning up a multidev for this branch to test in Drupal here (whenever it's done building) : https://github.com/yalesites-org/yalesites-project/pull/460

**Pull request merged**
