### PR TITLE
YSP-446: Drupal 10.3 upgrade with Node update and LinkPurpose

### PR DESCRIPTION
**Pull request by dblanken-yale**
### Description of work
- Updates to node (20.14.0)
- Updates to latest storybook (8.3.6)
- Applies linkpurpose over ys_links
- CSS changes to play nice with linkpurpose
- Convey that Qualtrics embeds are deprecated

### Testing Link(s)
- [ ] Navigate to the [All Component Stories](https://deploy-preview-429--dev-component-library-twig.netlify.app/)

### Functional Review Steps
- [x] Verify that storybook functions the way you would expect for each component
- [x] Verify that link treatments look good and that coloring is consistent with the rest of the links (unvisited, visited, hovered, visited-hovered)
- [x] Verify you see the inline message that Qualtrics is deprecated for any Qualtrics story.

### Design Review
- [ ] Verify the designs match the [Figma Designs](https://www.figma.com/file/OVfmCW5s1gI7xnrM8ibX2y/UI-Kit-Alpha-%5BYaleSites%5D)

### Accessibility Review
- [ ] Verify the component meets Accessibility requirements

### CODE REVIEW

**Review by miketullo95 — APPROVED** [review]
checked link treatments, embed qualtrics message, and overall visually checked each component 👍

**Comment by miketullo95** [comment]
> checked link treatments, embed qualtrics message, and overall visually checked each component 👍

wait i just found something quick. Callout on theme four links have the shadow bug

Screenshot 2024-10-23 at 11 08 58 AM

**Comment by kara-franco** [comment]
@ntay90 can you work with Dave to suggest colors that pass color contrast?

**Comment by dblanken-yale** [comment]
I'll push what I have so far as changes so we can see.  I haven't verified all is well with ONHA's yet, but plan to.

**Review by ntay90 — APPROVED** [review]
Worked with @dblanken-yale to resolve the issue with the link hover color. The colors for the themes look good a11y-wise on my end.

**Review by vinmassaro — APPROVED** [review]

**Pull request merged**
