### PR TITLE
YALB-1137: Dividers add new dials to divider block

### PR DESCRIPTION
**Pull request by dblanken-yale**
### Description of work
- Allow position and width to be set as part of the component itself
- Create CSS classes that mimic the manual styles used in Storybook before

### Testing Link(s)
- [ ] Navigate to the [Divider Component Story](https://deploy-preview-234--dev-component-library-twig.netlify.app/?path=/story/atoms-divider--dividers)

### Functional Review Steps
- [ ] Scroll down to the "Playground" section
- [ ] Click "Controls (4)" in the Show Addons panel (usually on the right side or bottom of page)
- [ ] Change the Divider width from "View-All" to "100"
- [ ] Take note of the length of the divider lines
- [ ] Change the Divider width from "100" to "25"
- [ ] Validate that the divider width changed to 25% of the 100 width
- [ ] Change the Divider width from "25" to "50"
- [ ] Validate that the divider width changed to 50% of the 100 width
- [ ] Change the Divider width from "50" to "75"
- [ ] Validate that the divider width changed to 75% of the 100 width
- [ ] Take note that the divider is located in the center of the Playground section
- [ ] Change the Divider position option from "center" to "left"
- [ ] Validate that the divider line now appears on the left side of the Playground instead of in the center
- [ ] Change the Divider position option from "left" to "center"
- [ ] Validate that the divider line now appears in the center of the Playground instead of the left side

### Design Review
- [ ] Verify the designs match the [Figma Designs](https://www.figma.com/file/OVfmCW5s1gI7xnrM8ibX2y/UI-Kit-Alpha-%5BYaleSites%5D)
- [ ] Review any new [Percy builds](https://percy.io/95144ff9/component-library-twig)

### Accessibility Review
- [ ] Verify the component still meets Accessibility requirements

### CODE REVIEW

**Comment by dblanken-yale** [comment]
Is there someone in particular I should add to pass Percy?

**Review by joetower — COMMENTED** [review]
@dblanken-yale For Percy, the changes just need to be reviewed and [approved in Percy](https://percy.io/95144ff9/component-library-twig/builds/27135694?utm_campaign=95144ff9&utm_content=component-library-twig&utm_source=github_status_public).

This all looks great to me, nice work! The one minor bit of feedback is to search the `component-library-twig` directory for instances of `divider__width` and change them to `divider__component_width` now that the variable name has changed. There should only be some matches in `05-page-examples` (e.g. `component-library-twig/components/05-page-examples/events/event-page.twig` ) but I figure we might as well get them changed now. :+1:  

With that search and replace, this looks good to go, to me. I see you have a draft PR for the atomic changes, awesome!

**Comment by dblanken-yale** [comment]
@joetower When I go into Percy, it has found items that I do not believe are from my change (says its comparing to develop 3 months ago), so I was hesitant to try to approve it myself.  I am unable to click the "approve build" button that I think I saw @myvaughn do before.  Any more guidance on that part?

I'll make those changes to the `divider__component_width` name right now.  Does that name convey what it should deal with?  Or do you think it should be something different?  Or, in an effort not to rename the original functionality, what do you feel might be a better name that would convey the divider width better?  divider__line_width?

I should probably also double check the other repos to make sure they're passing the correct name as well eh?  😁  I'll try to make note of that as well when I release those PRs.

**Review by kara-franco — APPROVED** [review]
Colors and code look great, nice work!

**Review by joetower — APPROVED** [review]
@dblanken-yale Thank you for making those changes. This looks good to ship!

For Percy, yeah, we need to refine the process here. Some page example snapshots have been removed and Percy hasn't been updated. A rule of thumb I follow here, is that I review the changes in Percy and so long as nothing marked as "changed" appears to be caused by the changes in your branch, then it's all good. Percy often times flags things as "changed" when `develop` has been merged into your branch being tested. 

I'm sure Mike V or Kara can get you the permissions needed to approve Percy builds. Let me know if you'd like to get access and approve it yourself or if, for the sake of merging this you would like me to review and approve the changes.

**Comment by joetower** [comment]
@dblanken-yale Oh and when you push another commit (like you just did), you have to mark your PR as a "draft" and then change it back to "ready for review", which triggers visual regression to re-test.

**Comment by joetower** [comment]
@dblanken-yale Ah, I forgot to answer your question. Yes, I think the naming makes sense. The `divider__component_width` is specific to the divider component container, while `divider__width` is more appropriate for affecting the divider itself. I can't think of anything more fitting. 

I'll take a look at Percy and approve the build. :+1:

**Comment by joetower** [comment]
@dblanken-yale Okay, I reviewed and approved Percy. Feel free to push the merge button whenever.

**Pull request merged**
