### PR TITLE
YALB-1563- Focus Header Variation

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- Adds `focus` variation as a site-header option (`site_header__type = 'focus'`) 
- Adds `focus` variation as a menu option (`site_header__menu__variation == 'focus'`)
- Sets the site header `site_header__type = 'focus'` if the menu variation is changed to `focus`. We don't currently have a use case to surface `site_header__type` as a variable, but we can easily extend this should we require another site_header__type in the future. 
- Adds the option to use an image for the site name instead of text (`site_header__site_name_is_image`)
- Adds the option to use a background image behind the `focus` site header

---

### Testing Link(s)
- [ ] Navigate to the [Site Header Component Story](https://deploy-preview-302--dev-component-library-twig.netlify.app/?path=/story/organisms-site-header--header)

### Functional Review Steps
- [x] Navigate to the site header component: https://deploy-preview-302--dev-component-library-twig.netlify.app/?path=/story/organisms-site-header--header
- [x] Verify you see an option for `Header: Menu Variation`
- [x] Verify you see an option for `With Image`
- [x] Verify that by selecting `focus` for `Header: Menu Variation`, you see a reduced version of the `basic` menu without dropdowns and without the `secondary` region of the header (Yale logo + utility menu).
- [x] Verify that the menu is centered vertically (with the site name) when the variation is set to `focus`
- [x] Test responsiveness

https://github.com/yalesites-org/component-library-twig/assets/366413/db6d8b42-d822-461f-a8c8-228d60db56e3

---

- [x] Verify you see an option for `Site Name Is An Image`
- [x] Test the menu variations and responsiveness when true

https://github.com/yalesites-org/component-library-twig/assets/366413/15e1f45c-6251-4691-9c89-3e5087670ff9

---

- [x] Test with Global themes with various configuration options: https://deploy-preview-302--dev-component-library-twig.netlify.app/?path=/story/tokens-colors--global-theme-color-pairings

https://github.com/yalesites-org/component-library-twig/assets/366413/3ad9cd01-a2cd-438d-ba51-ffcce5515bd8

---

### Design Review
- [ ] Verify the designs match the Figma Designs (but using the Global Theme colors and site-header themes): 

Simple Menu - examples

---
### Accessibility Review
- [ ] Verify the component meets Accessibility requirements
- [x] @kara-franco Specifically, do we need to add anything (`aria` or otherwise) to the site header logo's (will be an SVG) `a` element when we use an image as the site name instead of text? https://deploy-preview-302--dev-component-library-twig.netlify.app/?path=/story/tokens-colors--global-theme-color-pairings&args=globalTheme:two;menuVariation:focus;siteHeaderTheme:two;siteHeaderAccent:three;siteHeaderImage:true;siteHeaderSiteNameImage:true

Screenshot 2023-10-05 at 3 46 03 PM

---

### CODE REVIEW

**Review by codechefmarc — APPROVED** [review]
This looks so good - I played with a ton of the options and saw all the different versions. Neat stuff! Approved!

I was curious if there was a plan at some point to add more gradient colors as there may be some background images where the three gradients (white, black, and blue) aren't sufficient, but in all my tests it seemed to work just fine.

**Review by kara-franco — COMMENTED** [review]
Excellent work! For the linked svg version of the site logo we want to make sure the SVG has the proper role and name for screen reader users. 

- [x] We need to add ARIA `role=img`
- [x] Add a `<title>` that describes the destination of the link (e.g. Department of Chemistry)

Pattern #5 here is a great resource: [Pattern 5](https://www.smashingmagazine.com/2021/05/accessible-svg-patterns-comparison/#pattern-5-svg-role-img-title)

**Comment by joetower** [comment]
@kara-franco I added an example of an SVG instead of including a responsive image: https://deploy-preview-302--dev-component-library-twig.netlify.app/?path=/story/organisms-site-header--header&args=siteHeaderSiteNameImage:true

- `svg` has `role="img"`
- There is a `title` element inside the `svg` which renders the site name. 

If you inspect the page, when site name as image is true, you should see the following: 
Screenshot 2023-10-10 at 12 01 31 PM

**Comment by joetower** [comment]
@myvaughn Could you please take a look at Kara's feedback, confirm that I have addressed it, and review this PR and let us know if this ticket is a11y approved or if you have any additional feedback. Thank you!

**Review by myvaughn — CHANGES_REQUESTED** [review]
The svg attribute of role="img" and the <title> element look good.

When an image is included with the header (class="site-header__image"), I think in this case it should be marked decorative, unless you think a site author would ever include an image with this navigation option that conveyed important information? So either alt="" or add role="presentation".

Finally, I notice that if the "site name is an image" option is enabled, the site name does not appear in mobile view (unless I'm doing something wrong in my testing).

**Comment by myvaughn** [comment]
@joetower I meant to add the role="presentation" to the  element. Adding it to the enclosing <div> doesn't work. It looks like you can't easily modify the  attribute, so replace the `role="presentation"` with `aria-hidden="true"` on the <div> with the image. There won't be any other content in that <div>, right?

**Comment by joetower** [comment]
@myvaughn 🤦 Thank you for catching the mobile `site name as image' issue. With my last changes, based on Kara's feedback, I added an SVG as an example but forgot to adjust the mobile-specific markup. 

This is now fixed: https://deploy-preview-302--dev-component-library-twig.netlify.app/?path=/story/organisms-site-header--header&args=menuVariation:focus;siteHeaderImage:true;siteHeaderSiteNameImage:true

Screenshot 2023-10-11 at 1 00 01 PM

Also, I added `aria-hidden="true"` to the `site_header__image` element. At this time, this element will not contain anything other than the optional background image. 

Screenshot 2023-10-11 at 12 56 49 PM



Please take another look, thank you!

**Review by myvaughn — APPROVED** [review]
Changes look good.

**Review by dblanken-yale — APPROVED** [review]
Sorry this took so long!  This looks great!

**Review by kara-franco — APPROVED** [review]
Catching up, fixes look awesome!

**Comment by codechefmarc** [comment]
Just a note that the main [PR-469](https://github.com/yalesites-org/yalesites-project/pull/469) is now ready for review. I did make some minor edits to this PR for wiring. Once all has been approved over there, this one is good to merge as well.

**Pull request merged**
