### PR TITLE
YSP-569: V1.4.0 Spotlight in banner area has extra padding above

### PR DESCRIPTION
**Pull request by dblanken-yale**
### Description of work
- For controls we track for 'first', 'last', or 'first-and-last' positioning, we adjust the top margin to be 0

### Testing Link(s)
- [ ] Navigate to the [Content Spotlight Portrait](https://deploy-preview-382--dev-component-library-twig.netlify.app/?path=/story/molecules-content-spotlight--content-spotlight-portrait)
- [ ] Navigate to the [Content Spotlight Landscape](https://deploy-preview-382--dev-component-library-twig.netlify.app/?path=/story/molecules-content-spotlight--content-spotlight-landscape)
- [ ] Navigate to the [Basic Spotlight Example](https://deploy-preview-382--dev-component-library-twig.netlify.app/?path=/story/page-examples-standard-pages--basic-spotlights)
- [ ] Navigate to the [Banner Spotlight Example](https://deploy-preview-382--dev-component-library-twig.netlify.app/?path=/story/page-examples-standard-pages--basic-banner-spotlights)
- [ ] Navigate to the [Drupal site showing off spotlight in banner](https://pr-685-yalesites-platform.pantheonsite.io/daves-spotlight-test)
- [ ] Navigate to the [broken version](https://v140-yalesites-yale-edu.pantheonsite.io/ysp-538-test-page) to see what it used to look like

### Functional Review Steps
- [ ] Verify that Content Spotlight Portrait, Content Spotlight Landscape, and Basic Spotlight Example is not modified from the live version.
- [ ] Verify that Banner Spotlight Example's spotlight is bumping up to the header
- [ ] Verify that it looks ok in [Drupal](https://github.com/yalesites-org/yalesites-project/pull/685) or look at [my example page](https://pr-685-yalesites-platform.pantheonsite.io/daves-spotlight-test)

### Design Review
- [ ] Verify the designs match the [Figma Designs](https://www.figma.com/file/OVfmCW5s1gI7xnrM8ibX2y/UI-Kit-Alpha-%5BYaleSites%5D)
- [ ] Review any new [Percy builds](https://percy.io/95144ff9/component-library-twig)

### Accessibility Review
- [ ] Verify the component meets Accessibility requirements

### CODE REVIEW

**Comment by dblanken-yale** [comment]
I think the idea here is to accept this as is since it does fix this issue, and create a new ticket to refactor this into the layouts section.

**Review by vinmassaro — APPROVED** [review]
Visual review only looks good to me!

**Review by joetower — APPROVED** [review]
@dblanken-yale Approving to push this through (I did just see it get merged), but want to note that we should push a fast follow on this ticket that removes all of the `.layout--banner &` styles from this repository and moves it to: 
https://github.com/yalesites-org/atomic/blob/develop/css/layout-builder.css

So that these Drupal-only rules are set in this file only. Which, you'd essentially paste what you've added here, but zeroing out the top and bottom margin for any `spotlight` element within the `.layout--banner` section.

**Comment by dblanken-yale** [comment]
@joetower beat me to it adding that to here.  hahaha. Yep, I plan on creating a ticket to tackle this week to get it moved so we don't have to worry about it.  Thanks for adding that!  I'll get that created right now!

**Pull request merged**
