### PR TITLE
YALB-1562 - Color: Update tokens for existing color palettes

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- Add new color values by name

New Color Palettes

### Testing Link(s)
- [ ] Navigate to the [Color Tokens Component Story](https://deploy-preview-301--dev-component-library-twig.netlify.app/?path=/story/tokens-colors--colors)

### Functional Review Steps
- [x] Verify new colors are present: https://deploy-preview-301--dev-component-library-twig.netlify.app/?path=/story/tokens-colors--colors
- [x] Verify the global themes have been updated: https://deploy-preview-301--dev-component-library-twig.netlify.app/?path=/story/tokens-colors--color-global-themes
- [ ] Test new component color variations (header and footer accents): 
  - [ ] Header: https://deploy-preview-301--dev-component-library-twig.netlify.app/?path=/story/organisms-site-header--header-examples
    - [x] Verify you see 8 options for Header Accent
  - [ ] Footer: https://deploy-preview-301--dev-component-library-twig.netlify.app/?path=/story/organisms-site-footer--footer-examples
    - [x] Verify you see 8 options for Footer Accent
- [ ] Test all the components on this page: https://deploy-preview-301--dev-component-library-twig.netlify.app/?path=/story/tokens-colors--global-theme-color-pairings

https://github.com/yalesites-org/component-library-twig/assets/366413/f62bf7b4-ba82-4546-a686-9e3459dd49c1

### Design Review
- [ ] Verify the designs match the [Figma New Color Palettes](https://www.figma.com/proto/4Lx9A5sxO08DxUNbewalrR/Yale-Sites---ideation?type=design&node-id=536-8794&t=pMXV8sj8zjVsa5Bz-0&scaling=min-zoom&page-id=432%3A3352)

### Accessibility Review
- [ ] Verify the component meets Accessibility requirements

### CODE REVIEW

**Comment by kara-franco** [comment]
Awesome work!! I'm continuing to test the potential combinations with Levers and Dials. One thing I have noticed is that in the New haven Green palette, the focus indicators are not picking up the Slot 2 colors (they remain blue) and I've found a few focus indicator colors that should be white (due to a dark background). 

I'm also brainstorming how to best handle the colors in the menu. The current page color does not have enough visual distinction from the other page titles (in certain combinations). Not sure if we should just add an underline to the current page? 

Reference screenshots for focus indicators that need tweaking (*blue on yellow- blue needs to be darker): 
Screenshot 2023-09-29 at 1 00 17 PM
Screenshot 2023-09-29 at 1 00 22 PM
Screenshot 2023-09-29 at 1 06 38 PM

Reference screenshots for menu issues with current page: 
Screenshot 2023-09-29 at 1 50 40 PM
Screenshot 2023-09-29 at 1 51 25 PM
Screenshot 2023-09-29 at 1 54 23 PM

**Comment by kara-franco** [comment]
Also, an odd thing, may not be actionable, but worth noting- The hex codes from Figma vs the hex codes that Chrome renders are different. I know that the hex codes are being transformed into HSL, but curious as to why that happens. 

Example: 
Color Slot 3 in New Haven Green is 929E83 and in Chrome it is 939F84. 
Screenshot 2023-09-29 at 2 30 05 PM

**Comment by dblanken-yale** [comment]
@joetower I had a question regarding the Figma designs vs what you've implemented.  I wanted to attempt to verify the color accents match what was there, but I'm seeing things that are making it hard for me; like one Figma page shows 7 accent colors, not 8, but we have 8.  I think another talks about 10 colors.  Is there one that you used to go off of so I could understand that portion?  I went through and noticed that they are changing correctly, just wanted to ensure I understood more.

Looking at the one with 7 made me think you might have used each slot, making one extra?  I saw the one with 7 accents for header started at Slot 2 and didn't use 1.  Shot in the dark, but was trying to figure it out on my own.

**Comment by joetower** [comment]
@kara-franco I pushed up fixes for the `focus-visible` `outline` color to match those `white` and `gray-800` instances. Please take another look. Also, those hex differences are a known thing with the color picker. I don't think it's anything to worry about. 

@dblanken-yale FYI: I merged in your #300 ticket so that we minimize merge conflicts. I had to update the theme color-slots.

**Comment by dblanken-yale** [comment]
Oh darn, I just merged #300 into develop; hope that doesn't mess you up at all.

**Comment by joetower** [comment]
@dblanken-yale It breaks down like this: 
- slots 1-5 are the color slots that change between global theme
- slots 6-8 do not change. They are set to yale blue, gray-800, and white.

The header and footer accents are mapped in that way: 
- slots 1-5 are matched with each global theme slot with the same slot numbers
- slots 6-8 are yale blue, gray-800, and white
- Andrea/OPAC asked to have all 5 color slots along with yale blue, gray-800, and white available to use as accent colors on the header and footer. 

The CTA button themes only have 7 themes because there currently isn't a use case to use a white button when used alone (not in a callout or action banner, for example). For this reason, I did not include the 8th/ white theme for the Button CTA themes (in its tokens file). 
https://deploy-preview-301--dev-component-library-twig.netlify.app/?path=/story/atoms-controls--cta-examples

Please let me know if you'd like to discuss anything further.

**Comment by kara-franco** [comment]
Awesome, those focus indicator fixes are perfect, thank you! 

RE: menu active/current page colors- We need to discuss more with the team and get Katy's insight. [Harvard uses an underline and a highlight on their active/current page](https://college.harvard.edu/financial-aid/apply-financial-aid), but maybe there is something better we can do? Here is another example of the Slot 2 colors just not working (maybe we can have a standard menu treatment across all palettes?)

Screenshot 2023-09-29 at 4 00 22 PM

**Comment by joetower** [comment]
@kara-franco We could do an underline with a bit of thickness, like this: 

Screenshot 2023-09-29 at 3 17 04 PM

We can discuss this further in standup on Monday. 👍

**Review by nJim — APPROVED** [review]
We approved the color choices within a meeting. We would like to spend more time identifying potential contrast issues or even mitigate them by creating new button/link treatments -- but the goup is happy to see this move forward. My review of the backend code is that all changes look appropriate. Shipping it.

**Pull request merged**
