### PR TITLE
YALB-99: Site-footer component

### PR DESCRIPTION
**Pull request by ModulesUnraveled**
### Description of work
- Creates the Site Footer and places it in the layout

### Testing Link(s)
- [ ] [View the Site Footer Story](https://deploy-preview-21--dev-component-library-twig.netlify.app/?path=/story/organisms-site-footer--footer)
- [ ] [View the Site Footer Examples Story](https://deploy-preview-21--dev-component-library-twig.netlify.app/?path=/story/organisms-site-footer--footer-examples)
- [ ] [View the Full Width Story](https://deploy-preview-21--dev-component-library-twig.netlify.app/?path=/story/page-layouts-page-layouts--full-width)

### Functional Review Steps
- [ ] Verify things all look and function as expected

### Design Review
- [ ] Verify the designs match the [Figma Designs](https://www.figma.com/file/OVfmCW5s1gI7xnrM8ibX2y/UI-Kit-Alpha-%5BYaleSites%5D)

### Accessibility Review
- [ ] Verify the component meets Accessibility requirements

### CODE REVIEW

**Review by callinmullaney — DISMISSED** [review]
@ModulesUnraveled Looking good from a technical perspective.

**Comment by callinmullaney** [comment]
@ModulesUnraveled Actually, I commented too soon here. It looks like we need some adjustments for mobile. I didnt see specific designs in figma but we should probably make these elements stack at small sizes at the very least.

**Comment by ahitson** [comment]
Please make the divider line under the utility nav to be grey 300. If it needs to pass accessibility, then whatever is the first step into accomplishing that is cool with me.

**Comment by ahitson** [comment]
Footer links underline on hover, not while sitting. Please add 8px space between links/text and dividing bars, |.

Would like to see the mobile stacking logo / text / columns (only 1 column at a time) / social / privacy & accessibility links / copyright.

**Comment by ahitson** [comment]
There are some issues with the links. They should underline on hover. Some of the colorways are underlined before hover, the ones that are not, don't show a hover interaction.

**Review by callinmullaney — APPROVED** [review]
@ModulesUnraveled Mobile layout appears to be addressed and the solution you found to resolve the odd scope issue with `::after` looks good. I wonder if this will be a common issue for other components as the project progresses? We'll need to keep an eye on other implementations of the `::before` and `::after`. 

One thing I noticed here when viewing the mobile layout is about 40-70px prior to the switch the text in the footer breaks to a new line. However, the `|` is used as a link separator which obviously doesn't extend to the total height of the text. It seems a little awkward but I'll leave this up to you/Ashley to decide if it needs to be addressed in a different manner.
Screenshot from 2022-02-17 13-37-11

**Review by ahitson — APPROVED** [review]

**Comment by miketullo95** [comment]
- Would the inclusion of the Yale wordmark be included in this component since it would probably be included in all of the instances of this component? 

- This may be a bigger question, but what is the use case of the text under the wordmark? Was this included with something in mind?

**Review by kara-franco — CHANGES_REQUESTED** [review]
Looking good! The only display issue (not necessarily accessibility related) I found is when zoomed in on the page or at smaller screen sizes, the underline on hover is extended beyond the link text. 

Screen Shot 2022-02-18 at 10 09 26 AM

Steps to replicate: 
- Size viewport to 1280px and zoom in to 400%, or
- View at viewport width of ~575px.

**Comment by ModulesUnraveled** [comment]
@miketullo95 It's still not decided yet whether the logo will be the standard Yale one, or if it will be site/school specific in the footer. Once that's decided we can address it appropriately.
And the designs had a couple examples of text under the logo: https://www.figma.com/file/G4sJ0BLu4jCJpGzW82JHE8/YaleSites?node-id=930%3A1725

@kara-franco thanks! I actually noticed that during a screen share, but then forgot about it 🤦

**Review by miketullo95 — APPROVED** [review]
looks good from UX/front end!

**Review by kara-franco — APPROVED** [review]
Excellent, looks great!

**Pull request merged**
