### PR TITLE
YALB-488 - Links: Visited Link Styles 

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- Adds :visited link styles to in-page links
- Pulls in latest tokens release to get new purple visited colors
- Maps links used in dark background themes to use visited-light variations

### Testing Link(s)
- [x] Navigate to the [Accordion Component Story](https://deploy-preview-311--dev-component-library-twig.netlify.app/?path=/story/molecules-accordion--accordion) has links in each accordion item.
- [x] Verify they show up as `:visited` once you've clicked on one

### Functional Review Steps (I generated a test mutlidev to simplify testing)
- [x] Visit: https://pr-500-yalesites-platform.pantheonsite.io/fancy-lab
- [x] Click the `About the lab` link in the grand hero
- [x] Press the back button in your browser to go back to the fancy lab page. 
- [x] Verify that your clicked link is now purple
- [x] Go through the site and test various links. The visited link color _should_ apply to all links within the content area of the site and the footer links.  For example, this page has a lot of components: https://pr-500-yalesites-platform.pantheonsite.io/testing-all-of-the-things
- [ ] **Note:** 
  - [ ] Visited link styles do not apply to the header or menus. 
  - [ ] Also, they do not apply to button links

https://github.com/yalesites-org/component-library-twig/assets/366413/747770a7-2b07-40a9-887d-3184c5b2830c

- [x] Test different global themes (either by logging in and changing the global theme and component dial or in code like shown below) 

https://github.com/yalesites-org/component-library-twig/assets/366413/bc7d31a5-6c7c-4daa-aaec-c3f05a02ae62

### Accessibility Review
- [ ] Verify the component meets Accessibility requirements

### CODE REVIEW

**Review by dblanken-yale — APPROVED** [review]
Very nice work.  I was able to dive into the underline mixin also--pretty neat.

**Review by codechefmarc — APPROVED** [review]
Tested this on Arc (Chromium) and Safari and looks good to me! Tested header and footer links - only footer got the visited style, good. I like that cards got it as well.

Only question is the `package-lock.json` that is in this PR? Is that supposed to be there? I'm always confused when that needs to be added or not.

**Comment by joetower** [comment]
Thank you!

> Only question is the `package-lock.json` that is in this PR? Is that supposed to be there? I'm always confused when that needs to be added or not.

Yes, great question, this is here because I had to create a new tokens release (commit and merge new colors in the tokens repository) to get the new visited purple color values into a release to be able to be used in the component library. The change here updates the tokens release to the newest one, which includes the new colors.

**Review by kara-franco — APPROVED** [review]
Excellent work! I clicked and tabbed to so many links and all looked fantastic.

**Pull request merged**
