### PR TITLE
4) YALB-344: Heading and Page Title Components

### PR DESCRIPTION
**Pull request by ModulesUnraveled**
### Description of work
- Creates a generic Heading component
- Creates the Page Title component

### Testing Link(s)
- [ ] Navigate to the [Heading Examples story](https://deploy-preview-38--dev-component-library-twig.netlify.app/?path=/story/atoms-typography--headings-examples)
- [ ] Navigate to the [Page Title story](https://deploy-preview-38--dev-component-library-twig.netlify.app/?path=/story/molecules-page-title--page-title)
- [ ] Navigate to the [Standard Page](https://deploy-preview-38--dev-component-library-twig.netlify.app/?path=/story/page-examples-page-examples--standard-page)
- [ ] Navigate to the [News Article Page](https://deploy-preview-38--dev-component-library-twig.netlify.app/?path=/story/page-examples-page-examples--news-article)

### Functional Review Steps
- [ ] Verify the page title looks and functions correctly at all screen sizes

### Design Review
- [ ] Verify the designs match the [Figma Designs](https://www.figma.com/file/OVfmCW5s1gI7xnrM8ibX2y/UI-Kit-Alpha-%5BYaleSites%5D)

### Accessibility Review
- [ ] Verify the component meets Accessibility requirements

### CODE REVIEW

**Comment by miketullo95** [comment]
I believe there was a discussion about having the by-line and date be on separate lines for mobile to avoid widowing. 

Screen Shot 2022-03-04 at 3 23 54 PM

**Review by callinmullaney — APPROVED** [review]
@ModulesUnraveled I'm not seeing anything to address in this PR. Looks good!

**Comment by ModulesUnraveled** [comment]
@miketullo95 While I'm not sure we can programmatically avoid widowing entirely, I've set it to stack on "mobile" screens and remove the divider, so the majority of use-cases should work fine.

If you (or anyone else) is curious why I think we may not be able to guarantee this works for all situations, I'd be happy to jump on a zoom and do a demonstration

**Review by kara-franco — CHANGES_REQUESTED** [review]
Add aria-hidden="true" to the vertical line | in the meta title. The vertical bar is being announced by screen readers. 

Screen Shot 2022-03-08 at 9 27 14 AM

**Review by ahitson — APPROVED** [review]

**Review by kara-franco — APPROVED** [review]

**Pull request merged**
